spring.application.name=${APP_NAME:mallapi}

# =========================
# Database
# =========================
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
# =========================
# DB Pool
# =========================
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:1}
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE:5}

# =========================
# Multipart
# =========================
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:30MB}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}

# =========================
# Security Log
# =========================
logging.level.org.springframework.security.web=${SECURITY_LOG_LEVEL:info}

# =========================
# File Storage
# FILE_STORAGE_TYPE=local 또는 s3
# =========================
app.storage.type=${FILE_STORAGE_TYPE:local}
app.storage.local-path=${LOCAL_UPLOAD_PATH:/app/upload}

# =========================
# AWS S3
# FILE_STORAGE_TYPE=s3일 때 사용
# =========================
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}
cloud.aws.region.static=${AWS_REGION:ap-northeast-2}
cloud.aws.s3.bucket=${AWS_S3_BUCKET:}

# =========================
# Kakao Login
# =========================
kakao.rest-api-key=${KAKAO_REST_API_KEY}
kakao.client-secret=${KAKAO_CLIENT_SECRET}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}